In [1]:
import pandas as pd
import numpy as np
import math
import json
from datetime import date, timedelta
import urllib
import pickle
import xgboost as xgb
import requests

# ДЛЯ ДОСТУПА НА РАБОТЕ и не только
def get_json_from_url(url):
#     # Для работы
#         http_proxy  = "http://pavlov.ds:qwerty@172.16.0.10:3128"
#         https_proxy = "https://pavlov.ds:qwerty@172.16.0.10:3128"
#         ftp_proxy   = "ftp://pavlov.ds:qwerty@172.16.0.10:3128"

#         proxyDict = { 
#                       "http"  : http_proxy, 
#                       "https" : https_proxy, 
#                       "ftp"   : ftp_proxy
#                     }
#         r = requests.get(url, headers={'User-agent': 'Mozilla/5.0'}, proxies=proxyDict)
        
    # Дома
    r = requests.get(url, headers={'User-agent': 'Mozilla/5.0'})
        
    return json.loads(r.text)

# Для рейтинга команд
# создать мапу с старыми и новыми именами колонок для рейтинга команд
def name_columns(z1, elo):
    mapa = {}
    for index, key in enumerate(z1.keys()):
        mapa[key] = key + elo
    return mapa
# вытащить все данные по рейтингу (elo32, elo64, glicko, glicko2) одной команды
def get_data_team(data):
    ratings = ['elo32', 'elo64', 'glicko', 'glicko2']

    #Создать колонку с именем команды
    team = pd.DataFrame(columns=['team_Name'])
    team['team_Name'] = [data.get('teamName')]

    for rat in ratings:
        current_rating = data.get(rat)
        columns = name_columns(current_rating, '_' + rat)
        df = pd.DataFrame(data.get(rat), index=range(0,1))     
        df.rename(columns=columns, inplace=True)
        team = pd.DataFrame.merge(team, df, left_index=True, right_index=True)
    return team

#Для KDA Героевg
# Вытащить КДА по всем героям одной команды (нужна ссылка на сайт и массив из 5 героев одной команды)
def get_KDA(url, array_heroes):
    columns = ['hero', 'kills', 'deaths', 'assists', 'kda', 'avgKal', 'gpm', 'xpm', 'lastHits', 'denies', 'level',
           'heroDamage', 'towerDamage', 'heroHealing', 'goldSpent']
    # ДФ для соединения всех герове матча в один ДФ 
    df_heroe_match_teams = pd.DataFrame()

    # выгрзить json с предыдущей ссылки
    dat = get_json_from_url(url)
    df_data_tabel_for_heroes_radiant = pd.DataFrame(dat, columns=columns)
    df_kda_heroes = []
    for her in array_heroes:
        # достать KDA по каждому герою и убрать стобец с индексом героя
        kda_heroe = df_data_tabel_for_heroes_radiant[df_data_tabel_for_heroes_radiant['hero'] == her]
        kda_heroe = kda_heroe.drop('hero', axis=1)
        if len(kda_heroe) == 0:
            kda_heroe = [0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        df_kda_heroes = np.append(df_kda_heroes, kda_heroe)
    return df_kda_heroes

# Head_to_head
# добавить в массив суммарный показатель elo для героя vs всх врагов
def elo_heroes_vs_enemies(array_heroes, array_enemies, df_elo_herVsEne):
    df_elo = []
    # две переменные для записи суммарного elo каждой команды
    for her in array_heroes:
        hero_elo = 0
        # суммировать elo героя против героев противника
        for her_enemy in array_enemies:
            try:
                elo =  df_elo_herVsEne['shift'][df_elo_herVsEne['hero'] == 
                                              her][df_elo_herVsEne['againstHero'] == her_enemy].item()
                if math.isnan(elo):
                    elo=0
            except:
                elo=0
            hero_elo += elo
        # записать в основной массив elo по каждому герою
        df_elo = np.append(df_elo, hero_elo)
    return df_elo
# создать массив elo по героям имея только ссылку на сайт
def get_elo_head_to_head(url):
    # выгрзить json с предыдущей ссылки и создать ДФ
    dat = get_json_from_url(url)
    df_elo_herVsEne = pd.DataFrame(dat)
    
    radiant_eloVsEnemy = elo_heroes_vs_enemies(radiant, dire, df_elo_herVsEne)
    dire_eloVsEnemy = elo_heroes_vs_enemies(dire, radiant, df_elo_herVsEne)
    return np.append(radiant_eloVsEnemy, dire_eloVsEnemy)

#AvgElo
# вытащить ДФы для одного, пары, тройки героев из сайта по дате
def get_df_avgElo_heroes(df):
    # создать ДФ для одного героя, пары и тройки
    df_one = df.loc[(index for index, x in enumerate(df['heroes']) if len(x) == 1), :]  
    df_one = df_one.reset_index().drop('index', axis=1)
#     df_double = df.loc[(index for index, x in enumerate(df['heroes']) if len(x) == 2), :]  
#     df_triple = df.loc[(index for index, x in enumerate(df['heroes']) if len(x) == 3), :]  

    return df_one#, df_double, df_triple

# вытащить таблицу с elo героев для команды 
def get_df_AvgElo_heroes_teams(id_radiant_or_dire):
    # создать ссылку с данными по Avg.Elo для двух предыдущих месяцев игры
    url = ('http://www.datdota.com/api/heroes/elo?teams={}&tier=1&valve-event=does-not-matter&threshold=5'.format(id_radiant_or_dire) +
        '&patch=7.11&patch=7.10&patch=7.09&patch=7.08&patch=7.07&patch=7.06&patch=7.05&patch=7.04&patch=7.03&patch=7.02' + 
        '&patch=7.01&patch=7.00&patch=6.88&patch=6.87&patch=6.86&winner=either'+
        '&after=01%2F01%2F2011'+ 
        '&before={}%2F{}%2F{}'.format(date.today().day, date.today().month, date.today().year) + 
        '&duration=0%3B200&duration-value-from=0&duration-value-to=200')
    # выгрузить все с сайта и создать ДФ
    dat = get_json_from_url(url)
    df_url = pd.DataFrame(dat.get('data'))

    
    # создать ДФ для соло героев за все время игр команды (сигнатурки)
    return get_df_avgElo_heroes(df_url)



C:\Sneg\Add.Program\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
def last_patch(last):
    file =''
    for i in range(10,last+1):
        file += '&patch=7.'+str(i)
    return file   
print (last_patch(11))

&patch=7.10&patch=7.11


In [3]:
# Основная функция для предикта
def PREDICT(radiant_team_name, radiant_team_id, radiant, dire_team_name, dire_team_id, dire):
    # ВЫТАЩИТЬ из таблицы рейтинга пару героев
    # создать правильную ссылку для посика героев по команде radiant
    url = ('https://www.datdota.com/api/ratings')

    # выгрзить json с предыдущей ссылки и создать ДФ
    dat = get_json_from_url(url)
    data = dat.get('data')
    # создать DF для сохранения
    all_teams = pd.DataFrame()
    for i in data:   
        # убрать повторяющиеся команды (DC и Infamous и Effect(FlipSide))
        if (i.get('valveId') != 2512249) and (i.get('valveId') != 2672298) and (i.get('valveId') != 2790766):
            team = get_data_team(i) 
            all_teams = pd.concat([all_teams, team], ignore_index=True)
    all_teams = all_teams.drop(['phi_glicko', 'sigma_glicko2'],  axis=1)
    
    # Создание парметров для всех данных
    # вытащить рейтинги двух команд и убрать имя
    radiant_rating_df_allData = all_teams[all_teams['team_Name'] == radiant_team_name]
    radiant_rating_df_allData = radiant_rating_df_allData.drop(['team_Name'],  axis=1)

    dire_rating_df_allData = all_teams[all_teams['team_Name'] == dire_team_name]
    dire_rating_df_allData = dire_rating_df_allData.drop(['team_Name'],  axis=1)
    # соединить в один массив
    df_rating_teams_allData = np.append(radiant_rating_df_allData, dire_rating_df_allData ) 
    
    
    # Создание парметров для алгоритмов без ело32 и ело64
    # Оставляю только важные фичи, убираю из рейтинга команд ело32 и ело64
    all_teams_without_Elo = all_teams.drop(all_teams.loc[:, 'current_elo32':'thirtyDayAvg_elo64'], axis=1)

    # вытащить рейтинги двух команд и убрать имя
    radiant_rating_df_without_Elo = all_teams_without_Elo[all_teams_without_Elo['team_Name'] == radiant_team_name]
    radiant_rating_df_without_Elo = radiant_rating_df_without_Elo.drop(['team_Name'],  axis=1)
    print (len(radiant_rating_df_without_Elo))
    dire_rating_df_without_Elo = all_teams_without_Elo[all_teams_without_Elo['team_Name'] == dire_team_name]
    dire_rating_df_without_Elo = dire_rating_df_without_Elo.drop(['team_Name'],  axis=1)
    print (len(dire_rating_df_without_Elo))
    # соединить в один массив
    df_rating_teams_without_Elo = np.append(radiant_rating_df_without_Elo, dire_rating_df_without_Elo )
    print (len(df_rating_teams_without_Elo))
    
    
    #KDA Heroes
    url_kda_Heroes = ('http://www.datdota.com/api/heroes/performances?patch=7.11&patch=7.10&patch=7.09&patch=7.08&patch=7.07'+
                    '&patch=7.06&patch=7.05&patch=7.04&patch=7.03&patch=7.02&patch=7.01&patch=7.00'+
                  '&winner=either&after=01%2F01%2F2011&'+
                      'before={}%2F{}%2F{}&duration=0%3B200'.format(date.today().day, date.today().month, date.today().year)+
                  '&duration-value-from=0&duration-value-to=200&tier=1&valve-event=does-not-matter&threshold=10')
    radiant_kdaHeroes = get_KDA(url_kda_Heroes, radiant)
    dire_kdaHeroes = get_KDA(url_kda_Heroes, dire)
    # соединить всех героев в один массив
    df_kda_heroes = np.append(radiant_kdaHeroes, dire_kdaHeroes)
    print (len(df_kda_heroes))
    
    #KDA Teams
    # Radiant
    url_heroes_radiant =('http://www.datdota.com/api/heroes/performances?teams={}'.format(radiant_team_id) + 
                         '&patch=7.11&patch=7.10&patch=7.09&patch=7.08&patch=7.07&patch=7.06&patch=7.05&patch=7.04&patch=7.03'+
                         '&patch=7.02&patch=7.01&patch=7.00&winner=either&after=01%2F01%2F2011&'+
                         'before={}%2F{}%2F{}'.format(date.today().day, date.today().month, date.today().year)+
                         '&duration=0%3B200&duration-value-from=0&duration-value-to=200&tier=1&valve-event='+
                         'does-not-matter&threshold=1') 
    radiant_kdaHeroes = get_KDA(url_heroes_radiant, radiant)
    #Dire
    url_heroes_dire =('http://www.datdota.com/api/heroes/performances?teams={}'.format(dire_team_id) + 
                      '&patch=7.11&patch=7.10&patch=7.09&patch=7.08&patch=7.07&patch=7.06&patch=7.05&patch=7.04&patch=7.03'+
                      '&patch=7.02&patch=7.01&patch=7.00&winner=either&after=01%2F01%2F2011&'+
                      'before={}%2F{}%2F{}&'.format(date.today().day, date.today().month, date.today().year)+
                      'duration=0%3B200&duration-value-from=0&duration-value-to=200&tier=1&valve-event=does-not-matter'+
                      '&threshold=1') 
    dire_kdaHeroes = get_KDA(url_heroes_dire, dire)
    print (len(radiant_kdaHeroes))
    print (len(dire_kdaHeroes))
    df_kda_heroes_teams = np.append(radiant_kdaHeroes, dire_kdaHeroes)
    df_kda_heroes_teams = np.nan_to_num(df_kda_heroes_teams)
    
    
    
    # Elo героя относительно его врагов (Head-to_head)
    url_Head_to_head_allPatch = ('http://www.datdota.com/api/heroes/head-to-head-elo?tier=1&valve-event='+
                                 'does-not-matter&threshold=1&patch=7.11&patch=7.10&patch=7.09&patch=7.08&patch=7.07&patch=7.06'+
                                 '&patch=7.05&patch=7.04&patch=7.03&patch=7.02&patch=7.01&patch=7.00&patch=6.88&patch=6.87&'+
                                 'patch=6.86&patch=6.85&patch=6.84&patch=6.83&patch=6.82&patch=6.81&patch=6.80&patch=6.79&'+
                                 'patch=6.78&patch=6.77&patch=6.76&patch=6.75&patch=6.74&winner=either&after=01%2F01%2F2011&'+
                                 'before={}%2F{}%2F{}'.format(date.today().day, date.today().month, date.today().year)+
                                 '&duration=0%3B200&duration-value-from=0&duration-value-to=200')
    head_to_head_allPatch = get_elo_head_to_head(url_Head_to_head_allPatch)
    print (len(head_to_head_allPatch))


    # Метовые герои AvgElo
    # ДФ для соединения всех герове матча в один ДФ 
    df_heroes_match_AvgElo = []
    # создать дату два месяца назад от даты матча
    two_month_ago = date.today() - timedelta(60)
    # создать ссылку с данными по Avg.Elo для двух предыдущих месяцев игры
    url = ('http://www.datdota.com/api/heroes/elo?tier=1&valve-event=does-not-matter&threshold=10' +
        '&patch=7.11&patch=7.10&patch=7.09&patch=7.08&patch=7.07&patch=7.06&patch=7.05&patch=7.04&patch=7.03&patch=7.02' + 
        '&patch=7.01&patch=7.00&patch=6.88&patch=6.87&patch=6.86&winner=either'+
        '&after={}%2F{}%2F{}'.format(two_month_ago.day, two_month_ago.month, two_month_ago.year) + 
        '&before={}%2F{}%2F{}'.format(date.today().day, date.today().month, date.today().year) + 
        '&duration=0%3B200&duration-value-from=0&duration-value-to=200')
    # выгрузить все с сайта и создать ДФ
    dat = get_json_from_url(url)
    df_url = pd.DataFrame(dat.get('data'))
    # создать ДФ для одного героя за 2 предыдущих месяца
    df_data_tabel_for_heroes = get_df_avgElo_heroes(df_url)

    for her in (radiant + dire):
        # вытащить avg elo для данного героя
        avgElo_hero = df_data_tabel_for_heroes.loc[(index for index, x in enumerate(
                                            df_data_tabel_for_heroes['heroes']) if x == [her]),'eloShift']

        # проверить есть ли герой
        try:
            avgElo_hero = float(avgElo_hero)
        except:
            avgElo_hero = 0
        df_heroes_match_AvgElo.append(avgElo_hero)
    print(len(df_heroes_match_AvgElo))

    # ДФ для соединения всех герове матча в один ДФ 
    df_heroes_match_radiant = []
    df_heroes_match_dire = []
    # создать дату два месяца назад от даты матча
    two_month_ago = date.today() - timedelta(60)

    # RADIANT
    # создать ДФ для одного героя за 2 предыдущих месяца
    df_data_tabel_radiant = get_df_AvgElo_heroes_teams(radiant_team_id)

    for her in (radiant):
        # вытащить avg elo для данного героя
        avgElo_hero = df_data_tabel_radiant.loc[(index for index, x in enumerate(
                                            df_data_tabel_radiant['heroes']) if x == [her]),'eloShift']
        # проверить есть ли герой
        try:
            avgElo_hero = float(avgElo_hero)
        except:
            avgElo_hero = 0
        df_heroes_match_radiant.append(avgElo_hero)

    #DIRE
    # создать ДФ для одного героя за 2 предыдущих месяца
    df_data_tabel_dire = get_df_AvgElo_heroes_teams(dire_team_id)

    for her in (dire):
        # вытащить avg elo для данного героя
        avgElo_hero = df_data_tabel_dire.loc[(index for index, x in enumerate(
                                            df_data_tabel_dire['heroes']) if x == [her]),'eloShift']
        # проверить есть ли герой
        try:
            avgElo_hero = float(avgElo_hero)
        except:
            avgElo_hero = 0
        df_heroes_match_dire.append(avgElo_hero)
    df_heroes_teams_AvgElo = np.append(df_heroes_match_radiant, df_heroes_match_dire)
    print (len(df_heroes_teams_AvgElo))

    # Соединить все в один массив для предсказания без учета КДА, Ело32 и Ело64
    # Для данныз из head_to_head по всем патчам
    main_array_allPatch = np.append(df_rating_teams_without_Elo, head_to_head_allPatch)
    main_array_allPatch = np.append(main_array_allPatch, df_heroes_match_AvgElo)
    main_array_allPatch = np.append(main_array_allPatch, df_heroes_teams_AvgElo)
    Dmatrix_without_Elo = pd.DataFrame(main_array_allPatch, index=['radiant_mu_glicko', 'radiant_rating_glicko',
           'radiant_ratingSevenDaysAgo_glicko', 'radiant_sigma_glicko',
           'radiant_mu_glicko2', 'radiant_phi_glicko2', 'radiant_rating_glicko2',
           'radiant_ratingSevenDaysAgo_glicko2', 'dire_mu_glicko',
           'dire_rating_glicko', 'dire_ratingSevenDaysAgo_glicko',
           'dire_sigma_glicko', 'dire_mu_glicko2', 'dire_phi_glicko2',
           'dire_rating_glicko2', 'dire_ratingSevenDaysAgo_glicko2',
           'radiant_H1elo_vs_enemies', 'radiant_H2elo_vs_enemies',
           'radiant_H3elo_vs_enemies', 'radiant_H4elo_vs_enemies',
           'radiant_H5elo_vs_enemies', 'dire_H1elo_vs_enemies',
           'dire_H2elo_vs_enemies', 'dire_H3elo_vs_enemies',
           'dire_H4elo_vs_enemies', 'dire_H5elo_vs_enemies', 'radiant_H1_AvgElo_x',
           'radiant_H2_AvgElo_x', 'radiant_H3_AvgElo_x', 'radiant_H4_AvgElo_x',
           'radiant_H5_AvgElo_x', 'dire_H1_AvgElo_x', 'dire_H2_AvgElo_x',
           'dire_H3_AvgElo_x', 'dire_H4_AvgElo_x', 'dire_H5_AvgElo_x',
           'radiant_H1_AvgElo_y', 'radiant_H2_AvgElo_y', 'radiant_H3_AvgElo_y',
           'radiant_H4_AvgElo_y', 'radiant_H5_AvgElo_y', 'dire_H1_AvgElo_y',
           'dire_H2_AvgElo_y', 'dire_H3_AvgElo_y', 'dire_H4_AvgElo_y',
           'dire_H5_AvgElo_y']).T
    len(main_array_allPatch)
           
    # Соединить все в один массив для предсказания co всеми данными
    main_array_allPatch_allData = np.append(df_rating_teams_allData, df_kda_heroes)
    main_array_allPatch_allData = np.append(main_array_allPatch_allData, df_kda_heroes_teams)
    main_array_allPatch_allData = np.append(main_array_allPatch_allData, head_to_head_allPatch)
    main_array_allPatch_allData = np.append(main_array_allPatch_allData, df_heroes_match_AvgElo)
    main_array_allPatch_allData = np.append(main_array_allPatch_allData, df_heroes_teams_AvgElo)

    # Соединить все в один массив для предсказания без рейтинга команд
    main_array_allPatch_without_rating = np.append(head_to_head_allPatch, df_heroes_match_AvgElo)
    main_array_allPatch_without_rating = np.append(main_array_allPatch_without_rating, df_heroes_teams_AvgElo)
    Dmatrix_without_rating = pd.DataFrame(main_array_allPatch_without_rating, index=[
           'radiant_H1elo_vs_enemies', 'radiant_H2elo_vs_enemies',
           'radiant_H3elo_vs_enemies', 'radiant_H4elo_vs_enemies',
           'radiant_H5elo_vs_enemies', 'dire_H1elo_vs_enemies',
           'dire_H2elo_vs_enemies', 'dire_H3elo_vs_enemies',
           'dire_H4elo_vs_enemies', 'dire_H5elo_vs_enemies', 'radiant_H1_AvgElo_x',
           'radiant_H2_AvgElo_x', 'radiant_H3_AvgElo_x', 'radiant_H4_AvgElo_x',
           'radiant_H5_AvgElo_x', 'dire_H1_AvgElo_x', 'dire_H2_AvgElo_x',
           'dire_H3_AvgElo_x', 'dire_H4_AvgElo_x', 'dire_H5_AvgElo_x',
           'radiant_H1_AvgElo_y', 'radiant_H2_AvgElo_y', 'radiant_H3_AvgElo_y',
           'radiant_H4_AvgElo_y', 'radiant_H5_AvgElo_y', 'dire_H1_AvgElo_y',
           'dire_H2_AvgElo_y', 'dire_H3_AvgElo_y', 'dire_H4_AvgElo_y',
           'dire_H5_AvgElo_y']).T
    return (Dmatrix_without_Elo, Dmatrix_without_rating, main_array_allPatch, main_array_allPatch_allData)

# Исходные данные

In [4]:
df_teams_name_id = pd.read_csv('../Teams name and ID.csv', index_col=0)

list_heroes = pd.read_csv('../All_Heroes.csv')
np.array(list_heroes['localized_name'])

array(['Anti-Mage', 'Axe', 'Bane', 'Bloodseeker', 'Crystal Maiden',
       'Drow Ranger', 'Earthshaker', 'Juggernaut', 'Mirana', 'Morphling',
       'Shadow Fiend', 'Phantom Lancer', 'Puck', 'Pudge', 'Razor',
       'Sand King', 'Storm Spirit', 'Sven', 'Tiny', 'Vengeful Spirit',
       'Windranger', 'Zeus', 'Kunkka', 'Lina', 'Lion', 'Shadow Shaman',
       'Slardar', 'Tidehunter', 'Witch Doctor', 'Lich', 'Riki', 'Enigma',
       'Tinker', 'Sniper', 'Necrophos', 'Warlock', 'Beastmaster',
       'Queen of Pain', 'Venomancer', 'Faceless Void', 'Wraith King',
       'Death Prophet', 'Phantom Assassin', 'Pugna', 'Templar Assassin',
       'Viper', 'Luna', 'Dragon Knight', 'Dazzle', 'Clockwerk', 'Leshrac',
       "Nature's Prophet", 'Lifestealer', 'Dark Seer', 'Clinkz',
       'Omniknight', 'Enchantress', 'Huskar', 'Night Stalker',
       'Broodmother', 'Bounty Hunter', 'Weaver', 'Jakiro', 'Batrider',
       'Chen', 'Spectre', 'Ancient Apparition', 'Doom', 'Ursa',
       'Spirit Breaker', 'G

In [14]:
radiant_team_name =   "Vega Squadron" 
dire_team_name = 'Team. Spirit'

radiant_team_id =   2006913
dire_team_id =     2621843

radiant_H1 = list_heroes['id'][list_heroes['localized_name'] == "Earth Spirit"].item()
radiant_H2 = list_heroes['id'][list_heroes['localized_name'] == "Rubick"].item()
radiant_H3 = list_heroes['id'][list_heroes['localized_name'] == "Viper"].item()
radiant_H4 = list_heroes['id'][list_heroes['localized_name'] == "Underlord"].item()
radiant_H5 = list_heroes['id'][list_heroes['localized_name'] == "Lifestealer"].item()
dire_H1 = list_heroes['id'][list_heroes['localized_name'] == "Gyrocopter"].item()
dire_H2 = list_heroes['id'][list_heroes['localized_name'] == "Night Stalker"].item()
dire_H3 = list_heroes['id'][list_heroes['localized_name'] == "Bane"].item()
dire_H4 = list_heroes['id'][list_heroes['localized_name'] == "Lycan"].item()
dire_H5 = list_heroes['id'][list_heroes['localized_name'] == "Elder Titan"].item()

radiant = [radiant_H1, radiant_H2, radiant_H3, radiant_H4, radiant_H5]
dire = [dire_H1, dire_H2, dire_H3, dire_H4, dire_H5]

# Сбор всех таблиц
# Рейтинг команд

In [15]:
Dmatrix_without_Elo, Dmatrix_without_rating, main_array_allPatch, main_array_allPatch_allData = PREDICT(
    radiant_team_name, radiant_team_id, radiant, dire_team_name, dire_team_id, dire)

1
1
16
140
70
70
10
10
10


In [16]:
filename = 'grid_search_GB_model_allData_dayMatch.sav'
test_gb = pickle.load(open(filename, 'rb'))
print('Модель обученая На всех патчах до дня матча')
print (test_gb.predict([main_array_allPatch_allData]))
print (test_gb.predict_proba([main_array_allPatch_allData]))
print ('------------------------------------------------------------------------------------------------')

filename = 'grid_search_GB_model_allData_2018.05.06.sav'
test_gb = pickle.load(open(filename, 'rb'))
print('Модель обученая На всех патчах до 2018.05.06')
print (test_gb.predict([main_array_allPatch_allData]))
print (test_gb.predict_proba([main_array_allPatch_allData]))
print ('------------------------------------------------------------------------------------------------')

filename = 'xgb_all_data v.1.1 .sav'
test_gb = pickle.load(open(filename, 'rb'))
print('Модель xgb обученая На всех патчах до 2018.05.06')
print (test_gb.predict(Dmatrix_without_Elo))
print (test_gb.predict_proba(Dmatrix_without_Elo))
print ('------------------------------------------------------------------------------------------------')

filename = 'grid_search_GB_model v.1.1.b (day match without repeated rating teams) .sav'
test_gb = pickle.load(open(filename, 'rb'))
print('Модель обученая На всех патчах до дня матча без повторяющихся команд в таблице рейтинга')
print (test_gb.predict([main_array_allPatch]))
print (test_gb.predict_proba([main_array_allPatch]))
print ('------------------------------------------------------------------------------------------------')

filename = 'grid_search_GB_model v.1.1.a (day 12.02.18 without repeated rating teams) .sav'
test_gb = pickle.load(open(filename, 'rb'))
print('Модель обученая На всех патчах до 2018.05.06 без повторяющихся команд в таблице рейтинга')
print (test_gb.predict([main_array_allPatch]))
print (test_gb.predict_proba([main_array_allPatch]))

filename = 'xgb_all_data v.2.1.a (day 12.02.18 without repeated rating teams) .sav'
test_gb = pickle.load(open(filename, 'rb'))
print('Модель обученая На всех патчах до 2018.05.06 без повтор команд в таблице рейтинга без рейтинга команд (по пикам)')
print (test_gb.predict(Dmatrix_without_rating))
print (test_gb.predict_proba(Dmatrix_without_rating))


Модель обученая На всех патчах до дня матча
[1]
[[ 0.32518451  0.67481549]]
------------------------------------------------------------------------------------------------
Модель обученая На всех патчах до 2018.05.06
[0]
[[ 0.51691507  0.48308493]]
------------------------------------------------------------------------------------------------
Модель xgb обученая На всех патчах до 2018.05.06
[0]
[[ 0.69262183  0.30737814]]
------------------------------------------------------------------------------------------------
Модель обученая На всех патчах до дня матча без повторяющихся команд в таблице рейтинга
[0]
[[ 0.83527889  0.16472111]]
------------------------------------------------------------------------------------------------
Модель обученая На всех патчах до 2018.05.06 без повторяющихся команд в таблице рейтинга
[0]
[[ 0.87981985  0.12018015]]
Модель обученая На всех патчах до 2018.05.06 без повтор команд в таблице рейтинга без рейтинга команд (по пикам)
[0]
[[ 0.58561766  0.414